### PR TITLE
Added Bulgarian translation

### PR DESCRIPTION
**Pull request by twlvnn**
This pull request contains the Bulgarian translation for color-code. Please double-check if I added the language to the build process correctly to be sure.

### CODE REVIEW

**Comment by oyajun** [comment]
image
LC_ALL=bg_BG.UTF-8

**Comment by oyajun** [comment]
Thank you for your translating!
@twlvnn 
Could you tell me your name?
I want to write contributor names in this app.

**Comment by twlvnn** [comment]
I think it's a good idea to include names, but I prefer only a username instead.

**Comment by oyajun** [comment]
New version included your translations was released now!🎉
Check it out.

**Comment by twlvnn** [comment]
Will do, thank you so much!

**Pull request merged**
