### PR TITLE
Add Hindi translation

### PR DESCRIPTION
**Pull request by Scrambled777**
Initial Hindi `hi` language translation.

### CODE REVIEW

**Comment by oyajun** [comment]
Thank you!
@Scrambled777 
Could you tell me your name?
I want to write contributor names in this app.
It's OK real name or handle name.

**Comment by Scrambled777** [comment]
> Thank you! @Scrambled777 Could you tell me your name? I want to write contributor names in this app. It's OK real name or handle name.

Thanks for accepting my translation.

As for the name, could you pls include `Scrambled777`.

Cheers.

**Comment by oyajun** [comment]
memo: 
LC_ALL=hi_IN.UTF-8

**Comment by Scrambled777** [comment]
> memo: LC_ALL=hi_IN.UTF-8

Hi @oyajun, 

Is this memo for yourself or I need to do something?

**Comment by oyajun** [comment]
Sorry. This is a memo for myself.
It is the environment variable for testing translations

**Comment by Scrambled777** [comment]
> Sorry. This is a memo for myself. It is the environment variable for testing translations

Cool. I can relax now.😁

**Comment by oyajun** [comment]
New version included your translations was released now!🎉
Check it out.

**Pull request merged**
